---
sidebar: sidebar
permalink: partnercentral_adding_and_managing_customers.html
keywords:
summary:
---

= Adding and managing customers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-03-22 15:31:56.998625
//

[.lead]
Customers is the view where you can see your *Customer List*. In this view, you can add and modify customer information. 

If you want to add an existing tenant from SaaS Backup for Microsoft 365 into Partner Central, contact SaaS Backup Support at  mailto:saasbackupsupport@netapp.com[saasbackupsupport@netapp.com^]. 

Steps

. On the left, click Customers. 
. On the Customer List screen, click  to add a new customer. 
. In the pop up, click on the Office 365 icon to Create a New Customer Subscription.
. Enter the email address and password for your Microsoft 365 global administrator service account, and then click Sign in.
. A list of the permissions requested by SaaS Backup for Microsoft 365 is displayed.
. Click Accept. 
. Back in Partner Central, click  under Action in the Customer List to complete Customer Signup. 
. Input the requested user information. 
+
If this is a trial subscription, enter the activation code. 
+
If this is a licensed subscription, enter your NetApp SSO and product serial number. 

. Select Storage Selection options. 
+
If you are using storage provided by SaaS Backup: 

.. Click *SaaS Backup Provided Storage*.
.. Select the *Amazon S3* or *Azure Blob* storage option.
.. Select the *AWS S3* or *Azure Blob* region for your backup. You should select the region that is the closest to the physical location of the data you are backing up.
. Click *Create*. 
. A status update appears on the right side which reads “Customer Sign up In-Progress. ” When the status update is finished, the status changes to “Customer Sign up completed” and the status becomes Active. 
. Click  to redirect to SaaS Backup for the customer to Manage Customer’s Data using the SaaS Backup Dashboard. To return to Partner Central, click Partner Central under the customer’s name on the left side of the SaaS Backup user interface.
. For information about how to use SaaS Backup for Microsoft 365, go to NetApp%20SaaS%20Backup%20for%20Microsoft%20365%20online%20documentation[NetApp SaaS Backup for Microsoft 365 online documentation^] ( https://docs.netapp.com/us-en/saasbackupO365/[https://docs.netapp.com/us-en/saasbackupO365/^]).
